### ISSUE TITLE
The website link is outdated.

### ISSUE THREAD

**Issue by thomasrosen** [mikecao/react-basics#1]
I saw a storybook folder in the repository. But the linked website ([mikecao.github.io/react-basics/](https://mikecao.github.io/react-basics/)) returns a 404 error.

I think the link in the description needs to be updated to: [umami-software.github.io/react-basics/](https://umami-software.github.io/react-basics/)

Best, Thomas

**Comment by mikecao** [comment]
Thanks! Fixed now.
